### ISSUE TITLE
undefined reference

### ISSUE THREAD

**Issue by kassane** [alvarorichard/CortexC#1]
```bash
/usr/bin/ld: /tmp/ccWrJVA0.o: na função "function_declaration":
main.c:(.text+0x9e5): undefined reference to `function_parameter'
/usr/bin/ld: main.c:(.text+0xa03): undefined reference to `function_body'
collect2: error: ld returned 1 exit status
```
lib:
https://github.com/alvarorichard/CortexC/blob/b6363da809481fb77ba9c14a5a1c04a0e8eb6ddd/src/function_parameter.zig#L30

header
https://github.com/alvarorichard/CortexC/blob/b6363da809481fb77ba9c14a5a1c04a0e8eb6ddd/src/function_parameter.h#L1

main:
https://github.com/alvarorichard/CortexC/blob/b6363da809481fb77ba9c14a5a1c04a0e8eb6ddd/src/main.c#L369

rename to fix

cc: @alvarorichard

**Comment by kassane** [comment]
missing `function_body` function implementation!

Whats?
https://github.com/alvarorichard/CortexC/blob/b6363da809481fb77ba9c14a5a1c04a0e8eb6ddd/src/function_parameter.zig#L2  <= need `lib.linkLibC();` in `build.zig`

Please, replace:
```diff
- extern "C" fn next() void;
+ extern fn next() callconv(.C) void;
```
No exists libC (upper C)! callconv call OS libc.

https://github.com/alvarorichard/CortexC/blob/b6363da809481fb77ba9c14a5a1c04a0e8eb6ddd/src/build.zig#L7

missing 3thd param. Like it
```zig
const lib = b.addSharedLibrary("function_parameter", "function_parameter.zig", .unversioned);
```

**Comment by alvarorichard** [comment]
valeu pela ajuda

**Comment by alvarorichard** [comment]
tentei aplicar as mudanças sugeridas mas estou com mesmo erro acabei de subir um commit para ver as mudanças peço que verifique com atenção sou novo no mundo zig e tambem da programação e possivel que tenha errado aplicação das mudanças peço desculpas se for o caso mas acredito que nao seja isso
